package com.alessandro.appointment.model;


import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable, UserDetails {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String surname;
	private String email;
	private String password;
	private String competence;
	private String address;
	private String city;
	private String description;
	private String username;
	private Set ratingsForUserReceiver = new HashSet(0);
	private Set messagesForReceiver = new HashSet(0);
	private Set messagesForSender = new HashSet(0);
	private Set ratingsForUserSender = new HashSet(0);
	private Set appointments = new HashSet(0);
	private Set reservations = new HashSet(0);
	private List<Role> roles;
	private List<Role> authorities;
	private boolean accountNonExpired = true;
	private boolean accountNonLocked = true;
	private boolean credentialsNonExpired = true;
	private boolean enabled = true;
	
	public User() {
	}

	public User(String name, String surname, String email, String password, String competence, String address,
			String city, String description, String username, Set ratingsForUserReceiver, Set messagesForReceiver,
			Set messagesForSender, Set ratingsForUserSender, Set appointments, Set reservations) {
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.password = password;
		this.competence = competence;
		this.address = address;
		this.city = city;
		this.description = description;
		this.username = username;
		this.ratingsForUserReceiver = ratingsForUserReceiver;
		this.messagesForReceiver = messagesForReceiver;
		this.messagesForSender = messagesForSender;
		this.ratingsForUserSender = ratingsForUserSender;
		this.appointments = appointments;
		this.reservations = reservations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCompetence() {
		return this.competence;
	}

	public void setCompetence(String competence) {
		this.competence = competence;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Set getRatingsForUserReceiver() {
		return this.ratingsForUserReceiver;
	}

	public void setRatingsForUserReceiver(Set ratingsForUserReceiver) {
		this.ratingsForUserReceiver = ratingsForUserReceiver;
	}

	public Set getMessagesForReceiver() {
		return this.messagesForReceiver;
	}

	public void setMessagesForReceiver(Set messagesForReceiver) {
		this.messagesForReceiver = messagesForReceiver;
	}

	public Set getMessagesForSender() {
		return this.messagesForSender;
	}

	public void setMessagesForSender(Set messagesForSender) {
		this.messagesForSender = messagesForSender;
	}

	@JsonBackReference
	public Set getRatingsForUserSender() {
		return this.ratingsForUserSender;
	}

	public void setRatingsForUserSender(Set ratingsForUserSender) {
		this.ratingsForUserSender = ratingsForUserSender;
	}
	
	@JsonBackReference
	public Set getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set appointments) {
		this.appointments = appointments;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}
	

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}
	
	@JsonBackReference
	public List<Role> getAuthorities() {
        return authorities;
    }
    public void setAuthorities(List<Role> authorities) {
        this.authorities = authorities;
    }
    @JsonBackReference
    public boolean isAccountNonExpired() {
        return accountNonExpired;
    }
    public void setAccountNonExpired(boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }
    @JsonBackReference
    public boolean isAccountNonLocked() {
        return accountNonLocked;
    }
    public void setAccountNonLocked(boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }
    @JsonBackReference
    public boolean isCredentialsNonExpired() {
        return credentialsNonExpired;
    }
    public void setCredentialsNonExpired(boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }
    @JsonBackReference
    public boolean isEnabled() {
        return enabled;
    }
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
}
